from core.config import settings

# Expose settings directly for easy modular imports
OBSERVABILITY_ENABLED = settings.OBSERVABILITY_ENABLED
APP_ENV = settings.APP_ENV
APP_RELEASE = settings.APP_RELEASE or "unknown"
SERVICE_NAME = settings.SERVICE_NAME

SENTRY_BACKEND_DSN = settings.SENTRY_BACKEND_DSN
SENTRY_FRONTEND_DSN = settings.SENTRY_FRONTEND_DSN
SENTRY_EXTENSION_DSN = settings.SENTRY_EXTENSION_DSN
SENTRY_TRACES_SAMPLE_RATE = settings.SENTRY_TRACES_SAMPLE_RATE
SENTRY_PROFILES_SAMPLE_RATE = settings.SENTRY_PROFILES_SAMPLE_RATE

METRICS_ENABLED = settings.METRICS_ENABLED
METRICS_PATH = settings.METRICS_PATH
METRICS_BEARER_TOKEN = settings.METRICS_BEARER_TOKEN

GRAFANA_CLOUD_PROM_REMOTE_WRITE_URL = settings.GRAFANA_CLOUD_PROM_REMOTE_WRITE_URL
GRAFANA_CLOUD_PROM_USERNAME = settings.GRAFANA_CLOUD_PROM_USERNAME
GRAFANA_CLOUD_PROM_API_KEY = settings.GRAFANA_CLOUD_PROM_API_KEY
GRAFANA_CLOUD_PROM_PUSH_INTERVAL_SECONDS = settings.GRAFANA_CLOUD_PROM_PUSH_INTERVAL_SECONDS

OTEL_ENABLED = settings.OTEL_ENABLED
OTEL_SERVICE_NAME = settings.OTEL_SERVICE_NAME
OTEL_EXPORTER_OTLP_ENDPOINT = settings.OTEL_EXPORTER_OTLP_ENDPOINT
OTEL_EXPORTER_OTLP_HEADERS = settings.OTEL_EXPORTER_OTLP_HEADERS
OTEL_EXPORTER_OTLP_PROTOCOL = settings.OTEL_EXPORTER_OTLP_PROTOCOL
OTEL_TRACES_SAMPLER = settings.OTEL_TRACES_SAMPLER
OTEL_TRACES_SAMPLER_ARG = settings.OTEL_TRACES_SAMPLER_ARG

LOG_LEVEL = settings.LOG_LEVEL
LOG_FORMAT = settings.LOG_FORMAT
